[book]
authors = ["Adam Bates"]
language = "en"
multilingual = false
src = "src"
title = "Ferrum Programming Language"

[output.html]
default-theme = "navy"
preferred-dark-theme = "navy"
git-repository-url = "https://github.com/ferrum-lang/ferrum"
cname = "ferrum-lang.org"

[output.html.print]
enable = false

[output.html.fold]
enable = false    # whether or not to enable section folding
level = 0         # the depth to start folding
